import os
DIRECTORY = os.getcwd()

BN_ACCESS_KEY_AWS = 'k6YQiFK0UZPUkreaWbddBzlKp4f9l7RPteM8Dq0hFWKTqkyjsSTZRGnsK5SkQCNa'
BN_SECRET_KEY_AWS = 'e5Akp75hIopjlhRGFnDuLnzT3k1oY789rBIC6Im1GbXefYgZHT5CvHMtsHx02yOl'
BN_IP_AWS = '3.37.89.67'

BN_ACCESS_KEY_NAJU = 'k6YQiFK0UZPUkreaWbddBzlKp4f9l7RPteM8Dq0hFWKTqkyjsSTZRGnsK5SkQCNa'
BN_SECRET_KEY_NAJU = 'e5Akp75hIopjlhRGFnDuLnzT3k1oY789rBIC6Im1GbXefYgZHT5CvHMtsHx02yOl'
BN_IP_NAJU = '58.125.138.167'

UB_ACCESS_KEY_NAJU = 'dGZaKiwwfCu3znS8vkOAt0J8QWnVUlZh4LXlA1vs'
UB_SECRET_KEY_NAJU = 'uzYHzPwKkyeRDsxDyDFJEcJLgJPV7eeo65hPtxSd'
UB_IP_NAJU = '58.125.138.167'

UB_ACCESS_KEY_AWS = 'DSFClZsOVLbkjL31uZdwLlsU3adyQoE9fWsuhhMN'
UB_SECRET_KEY_AWS = '3x0vv6PyRzm1wRczWqxYqdHmQRgEP0OczHijCveB'
UB_IP_AWS = '43.201.99.220'

LINE_URL = 'https://notify-api.line.me/api/notify'
LINE_TOKEN = '48zl8RmuB0lZoPOoVmqowZzjsUE0P53JO7jfVFCyLwh'

FILE_URL = DIRECTORY + '/_d'
FILE_URL_BLNC_3M = FILE_URL + '/BalanceList.pickle'
FILE_URL_TIKR_3M = FILE_URL + '/TickerRealStatus.pickle'
FILE_URL_PRFT_3M = FILE_URL + '/ProfitList.pickle'

FILE_URL_TEST = DIRECTORY + '/_d_t'
FILE_URL_TEST_TIKR_3M = FILE_URL_TEST + '/TestTickerList.pickle'